version: "2"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  app:
    image: golang:1.15
    environment:
      DB_HOST: db
    command: "go run server.go"
    volumes:
      - ./:/go/src
    working_dir: /go/src
    ports:
      - "8080:8080"
    links:
      - db

volumes:
  db-data:
